site_name: "Exploring Python"
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: amber
  logo: images/exploring_python.png
  favicon: images/exploring_python.png
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.highlight
    - content.tooltips
    - content.code.mermaid

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.highlight
  - attr_list

nav:
  - Home: index.md
  - Basics:
    - Data Types:
        - Strings: basics/data_types/strings.md
        - Integers: basics/data_types/ints.md
        - Floating Point Numbers: basics/data_types/floats.md
        - Booleans: basics/data_types/booleans.md
    - Control Structures:
        - If Statements: basics/control_structures/if_statements.md
        - For Loops: basics/control_structures/for_loops.md
        - While Loops: basics/control_structures/while_loops.md
        - Controlling Loops: basics/control_structures/controlling_loops.md
        - Comprehensions: basics/control_structures/comprehensions.md
        - Functions: basics/control_structures/functions.md
    - Data Structures:
        - Lists: basics/data_structures/lists.md
        - Tuples: basics/data_structures/tuples.md
        - Dictionaries: basics/data_structures/dictionaries.md
        - Sets: basics/data_structures/sets.md
        - Membership Testing: basics/data_structures/membership_testing.md
        - Slicing Sequences: basics/data_structures/slicing_sequences.md
  - Intermediate:
      - Iterators and Generators: intermediate/iterators_and_generators.md
